name             'homebrew'
maintainer       'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license          'Apache 2.0'
description      'Install Homebrew, and use it as the OS X package provider on Chef versions =< 11'
version          '1.12.0'
recipe           'homebrew', 'Install Homebrew'
supports         'mac_os_x'
supports         'mac_os_x_server'
depends          'build-essential', '>= 2.1.2'
