name             'homebrew'
maintainer       'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license          'Apache-2.0'
description      'Install Homebrew and includes resources for working with taps and casks'
version          '5.3.1'
supports         'mac_os_x'

source_url 'https://github.com/chef-cookbooks/homebrew'
issues_url 'https://github.com/chef-cookbooks/homebrew/issues'
chef_version '>= 12.15'
