---
name: ci

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@8.0.4
    with:
      platform: macos-latest
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    if: always()
    runs-on: macos-latest
    strategy:
      matrix:
        os:
          - macos-latest
        suite:
          - default
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Install Cinc Workstation
        uses: sous-chefs/.github/.github/actions/install-workstation@8.0.4

      - name: Test Kitchen
        uses: actionshub/test-kitchen@3.0.0
        env:
          KITCHEN_LOCAL_YAML: kitchen.exec.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}

  final:
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Complete
        run: echo "All tests passed"
